version: '3.2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - flask-volume:/code

   
        depends_on:
            - redis
    redis:
        image: redis
volumes:
    flask-volume:
        external: false
